# Generated by Django 4.1.2 on 2022-10-20 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genero', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12)),
                ('sobrenome', models.CharField(max_length=15)),
                ('admissão', models.DateField()),
                ('idade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)])),
                ('genero2', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('NA', 'Prefiro não opinar')], max_length=30)),
                ('aniversário', models.DateField()),
                ('endereço', models.CharField(max_length=75)),
                ('CPF', models.IntegerField()),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='webpage.genero')),
                ('cargo', models.ForeignKey(blank=True, default='Sem_cargo_denifido', null=True, on_delete=django.db.models.deletion.RESTRICT, to='webpage.cargo')),
            ],
        ),
    ]
