# Generated by Django 4.1.1 on 2022-10-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employeeInfo',
            new_name='FuncionariosInformaçoes',
        ),
    ]
