# Generated by Django 4.1.1 on 2022-10-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_rename_employeeinfo_funcionariosinformaçoes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuncionariosInformaçoes',
            new_name='Funcionario',
        ),
    ]
