# Generated by Django 4.1.2 on 2022-10-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_rename_genero2_funcionario_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=32),
        ),
    ]
