# Generated by Django 4.1.1 on 2022-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_rename_funcionariosinformaçoes_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
    ]
