# Generated by Django 4.1.1 on 2022-10-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_alter_funcionario_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='endereço',
            field=models.CharField(max_length=75),
        ),
    ]
