# Generated by Django 4.1.2 on 2022-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_alter_funcionario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(max_length=32),
        ),
    ]
