# Generated by Django 4.1.2 on 2022-10-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_alter_funcionario_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('entrada_manhã', models.TimeField(default=None, null=True)),
                ('saida_manhã', models.TimeField(default=None, null=True)),
                ('entrada_tarde', models.TimeField(default=None, null=True)),
                ('saida_tarde', models.TimeField(default=None, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='webpage.funcionario')),
            ],
        ),
    ]
