# Generated by Django 4.1.2 on 2022-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='entrada_manhã',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='entrada_tarde',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='saida_manhã',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='saida_tarde',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
