# Generated by Django 4.1.1 on 2022-10-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_funcionario_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='sexo',
            new_name='gênero',
        ),
    ]
