# Generated by Django 4.1.2 on 2022-10-20 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_alter_checkin_entrada_manhã_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='entrada_manhã',
            new_name='entrada_manha',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='saida_manhã',
            new_name='saida_manha',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='checkin', to='webpage.funcionario'),
        ),
    ]
