# Generated by Django 4.1.2 on 2022-10-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_rename_entrada_manhã_checkin_entrada_manha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('NA', 'Prefiro não opinar')], max_length=30),
        ),
    ]
