# Generated by Django 4.1.2 on 2022-10-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_alter_checkin_dia_alter_checkin_entrada_manha_and_more'),
        ('webpage', '0010_alter_checkin_dia_alter_checkin_funcionario'),
    ]

    operations = [
    ]
